package co.edu.iudigital.helpmeiud.models;

import lombok.Getter;
import lombok.Setter;
import lombok.experimental.FieldDefaults;
import lombok.AccessLevel;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "roles")
@Getter @Setter
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Role implements Serializable {

    static final long serialVersionUID = 1L;

    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    Long id;

    @Column(unique = true, length = 100)
    String name;

    @Column
    String description;

    // Getters and setters are automatically generated by Lombok
}
