server:
  port: 8084
  servlet:
    context-path: /api/v1
spring:
  application:
    name: helpmeiud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helpme_iud
    username: codentide
    password: acertijo21
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: <template@sendermail.com>
    password: <sendermailpassword>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #FILES
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#SECURITY
security:
  jwt:
    client-service: HelpmeIUD
    password-service: 123456
    scope-read: read
    scope-write: write
    grant-password: password
    grant-refresh: refresh_token
    token-validity-seconds: 3600
    refresh-validity-seconds: 3600
